<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="446" started-at="2020-09-22T06:35:46Z" finished-at="2020-09-22T06:35:47Z">
    <groups>
    </groups>
    <test name="TestExtent" duration-ms="446" started-at="2020-09-22T06:35:46Z" finished-at="2020-09-22T06:35:47Z">
      <class name="org.extentreport.extenttest">
        <test-method status="PASS" signature="startExtentTest()[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="startExtentTest" is-config="true" duration-ms="178" started-at="2020-09-22T12:05:46Z" finished-at="2020-09-22T12:05:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startExtentTest -->
        <test-method status="FAIL" signature="failTest(java.lang.reflect.Method)[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="failTest" duration-ms="9" started-at="2020-09-22T12:05:46Z" finished-at="2020-09-22T12:05:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void org.extentreport.extenttest.failTest(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [i] but found [we]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [i] but found [we]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at org.extentreport.extenttest.failTest(extenttest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="getResult" is-config="true" duration-ms="13" started-at="2020-09-22T12:05:46Z" finished-at="2020-09-22T12:05:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=failTest status=FAILURE method=extenttest.failTest(java.lang.reflect.Method)[pri:0, instance:org.extentreport.extenttest@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="passTest(java.lang.reflect.Method)[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="passTest" duration-ms="8" started-at="2020-09-22T12:05:47Z" finished-at="2020-09-22T12:05:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void org.extentreport.extenttest.passTest(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passTest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="getResult" is-config="true" duration-ms="0" started-at="2020-09-22T12:05:47Z" finished-at="2020-09-22T12:05:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passTest status=SUCCESS method=extenttest.passTest(java.lang.reflect.Method)[pri:0, instance:org.extentreport.extenttest@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="skiptest(java.lang.reflect.Method)[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="skiptest" duration-ms="0" started-at="2020-09-22T12:05:47Z" finished-at="2020-09-22T12:05:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void org.extentreport.extenttest.skiptest(java.lang.reflect.Method)]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping thi test]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping thi test
	at org.extentreport.extenttest.skiptest(extenttest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skiptest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="getResult" is-config="true" duration-ms="0" started-at="2020-09-22T12:05:47Z" finished-at="2020-09-22T12:05:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=skiptest status=SKIP method=extenttest.skiptest(java.lang.reflect.Method)[pri:0, instance:org.extentreport.extenttest@7d9d1a19] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="endextentTets()[pri:0, instance:org.extentreport.extenttest@7d9d1a19]" name="endextentTets" is-config="true" duration-ms="220" started-at="2020-09-22T12:05:47Z" finished-at="2020-09-22T12:05:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endextentTets -->
      </class> <!-- org.extentreport.extenttest -->
    </test> <!-- TestExtent -->
  </suite> <!-- Suite -->
</testng-results>
